runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /, /(.*)
  static_files: www/index.html, www/\1
  upload: www/index.html, www/(.*)

- url: /.*
  script: mod_rewrite.php

mod_rewrite.php:

$path = parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH);
if (dirname($path) == '/' && pathinfo($path, PATHINFO_EXTENSION) == 'html') {
  $file = pathinfo($path, PATHINFO_BASENAME);
}
else {
  $file = 'index.html
}

$_SERVER['SCRIPT_NAME'] = '/' . $file;
require $file;